version: "3.8"
services:
  app:
    build:
      context: ./
    restart: 'no'
    networks:
      - dgraphnet
    # environment:
      # DB_HOST: db:8080
      # LOG_LEVEL: DEBUG
    depends_on:
      db_init:
        condition: service_completed_successfully
    user: root # For attaching VSCode
    env_file:
      - ./.env
    # command: tail -f /dev/null
    # volumes:
    #   - ./app/src:/app

  dspacer: 
    image: ghcr.io/sustainability-zhaw/extraction-dspace:sha-e48a854
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    configs:
      - source: dcconfig
        target: /etc/app/config.json

  db:
    image: dgraph/standalone:v22.0.2
    restart: 'no'
    networks:
      - dgraphnet
    
  db_init:
    image: ghcr.io/sustainability-zhaw/dgraph-schema:sha-3914aa2
    restart: 'no'
    networks:
      - dgraphnet
    environment:
      TIMEOUT: 25
      DGRAPH_SERVER: http://db:8080
      # SAMPLE_DATA: plain_pubs

networks:
  dgraphnet:

configs:
  dcconfig:
    file: ./contrib/digital_collection.json
